### ISSUE TITLE
关于抓取所有美服商品getAllAmericaGoods()

### ISSUE THREAD

**Issue by cove1205** [Luobro/eshop#1]
你好，我最近也在研究eshop游戏数据抓取。看到你的这个项目，就学习了一下。
关于getAllAmericaGoods()这个函数有几个问题：
getAllAmericaGoods()的实现逻辑是将全部商品按照价格facet进行拆分，每种价格范围作为一次筛选请求多次，从而将获得的数据拼装为全部数据。但是，根据观察，我发现这么几个问题：
1. 简单检验了官网的筛选条件，发现在其他条件固定的情况下，按照价格分别筛选获得的总数会比不筛选价格时要少，大约少50左右。
2. 即使筛选条件为（switch平台、在售）的情况下，仍然有几个价格区间的游戏总数大约1000，无法一次性获取，可能还需要进一步按照ESRB分级进行筛选。（应该是可行的，但是感觉这样就太繁琐了）

因为我没有TS的使用经验，所以对getAllAmericaGoods()的理解如果有误的话请见谅。
下图中可以看到当前ns在售游戏有3747，但是所有价格区间的加起来要少，按道理说价格区间是互斥的，不应该发生这个问题。。暂时还没弄明白。
 
![20200611002336](https://user-images.githubusercontent.com/4844617/84293056-d91a6680-ab79-11ea-9982-b6b7a5c7e5a1.jpg)

**Comment by Luobro** [comment]
你好，我除了筛选平台外，还筛选了 How to shop 为 On Nintendo.com ，即能够在线购买的数字版商品，见 [代码](https://github.com/Luobro/eshop/blob/756f0ef6d7a7ae144345f1a41391bfc73d232e6d/src/lib/us.ts#L50) 如此按价格纬度查找，就全都是少于1000的了。

至于数量差异，我没有进行认真的校对。

**Comment by cove1205** [comment]
感谢你的回答。我又尝试添加了How to shop 为 On Nintendo.com的筛选方式。但是这个filter返回的结果很迷，它过滤掉了很多本来应该能被搜索到的游戏。比如FF12（final-fantasy-xii-the-zodiac-age-switch），是可以在官网和eshop里被搜索并购买的，但是使用 On Nintendo.com条件就被筛除了。
然后解析游戏数据时发现，有的游戏的filterShops里只有实体标签，但是也可以在线购买。。
```json
-"filterShops": [
    "At retail"
 ],
```
所以个人认为这个On Nintendo.com方式是有点问题的

**Comment by Luobro** [comment]
这个倒是之前没有考虑到的。不知道方便加下好友交流不？我的微信号是：luobrother
